name: Test Coverage and Echo Result

on:
  push:
    branches:
      - 'main'

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: List files for debugging
        run: ls -R

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: |
          npm run test -- --coverage
          COVERAGE_PERCENT=$(cat ./path/to/coverage/folder/lcov-report/index.html | grep -oP '(?<=<span class="strong">)[0-9]*(?=%<\/span> total)')
          echo "Coverage: $COVERAGE_PERCENT%"
